### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by jcockhren** [nss-evening-cohort-3/mathmagician-group-project-dr-moneysack-and-friend-s#6]

**Comment by mattbruton** [comment]
#13 UI is functional, but current issues are there is nothing in place to limit amount of numbers generated and user can currently enter a non-number as the amount to generate.

Will need to update with Command classes as they're merged into master branch.

**Comment by mattbruton** [comment]
Fixed issues with Program.cs and the accompanying BranchingLogic.cs files from earlier. Pending PR should work well enough.

**Comment by mattbruton** [comment]
Need to add classes to UserInterface.cs as they are merged into master branch.
